### ISSUE TITLE
Hey bro

### ISSUE THREAD

**Issue by Synaxis** [zeroKilo/X360DebuggerWV#1]
hey i couldn't find you at reddit 
do you have discord ?   pls add me Synaxis #0979  
or https://discord.gg/aHXeweX 
Here is the source for the Emulator we are using. 
[Nbackend.zip]
(https://github.com/zeroKilo/X360DebuggerWV/files/1504175/Nbackend.zip)

**Comment by zeroKilo** [comment]
https://www.reddit.com/user/WarrantyVoider/ I dont think you really searched, sry im not on discord
